"""Notifications module - handles user notifications and data management"""

import logging

from .users import (
    users_data,
    load_users_data,
    save_users_data,
    get_user_status,
    set_user_group,
    toggle_notification,
    is_notification_enabled,
    set_user_language,
    get_user_language,
    set_user_ui_language,
    get_user_ui_language,
    get_user_timezone,
    set_user_timezone,
    set_user_website_mode,
    get_user_website_mode,
    mark_quali_done,
    reset_user_status,
    update_user_profile,
    get_user_profile,
    mark_user_blocked,
    is_user_blocked,
    unblock_user,
    add_snooze_reminder,
    remove_snooze_reminder,
    remove_snooze_reminder_by_time,
    get_all_snooze_reminders,
    get_all_active_snoozes,
    remove_active_snooze,
    get_snooze_count,
    increment_snooze_count,
    reset_snooze_count,
    reset_snooze_counts_for_deadline_passed,
    LANGUAGE_OPTIONS,
    DEFAULT_USER_LANG,
    SNOOZE_TOLERANCE_SECONDS,
    SNOOZE_MAX_COUNTS,
)
from .validation import (
    parse_time_input,
    validate_custom_notification_hours,
    validate_group_input,
    format_custom_notification_time,
    get_custom_notifications,
    set_custom_notification,
    CUSTOM_NOTIF_MIN_HOURS,
    CUSTOM_NOTIF_MAX_HOURS,
    GROUP_RANGES,
)
from .senders import (
    send_notification_to_user,
    send_quali_notification,
    send_race_live_notification,
    send_race_replay_notification,
    send_race_results_notification,
    send_quali_results_notification,
    send_new_season_reminder_notification,
)
from .utils import format_weather_data
from .checker import check_notifications

__all__ = [
    # User data
    "users_data",
    "load_users_data",
    "save_users_data",
    "get_user_status",
    "set_user_group",
    "toggle_notification",
    "is_notification_enabled",
    "set_user_language",
    "get_user_language",
    "set_user_ui_language",
    "get_user_ui_language",
    "get_user_timezone",
    "set_user_timezone",
    "set_user_website_mode",
    "get_user_website_mode",
    "mark_quali_done",
    "reset_user_status",
    "update_user_profile",
    "get_user_profile",
    "mark_user_blocked",
    "is_user_blocked",
    "unblock_user",
    "add_snooze_reminder",
    "remove_snooze_reminder",
    "remove_snooze_reminder_by_time",
    "get_all_snooze_reminders",
    "get_all_active_snoozes",
    "remove_active_snooze",
    "get_snooze_count",
    "increment_snooze_count",
    "reset_snooze_count",
    "reset_snooze_counts_for_deadline_passed",
    "LANGUAGE_OPTIONS",
    "DEFAULT_USER_LANG",
    "SNOOZE_TOLERANCE_SECONDS",
    "SNOOZE_MAX_COUNTS",
    # Validation
    "parse_time_input",
    "validate_custom_notification_hours",
    "validate_group_input",
    "format_custom_notification_time",
    "get_custom_notifications",
    "set_custom_notification",
    "CUSTOM_NOTIF_MIN_HOURS",
    "CUSTOM_NOTIF_MAX_HOURS",
    "GROUP_RANGES",
    # Senders
    "send_notification_to_user",
    "send_quali_notification",
    "send_race_live_notification",
    "send_race_replay_notification",
    "send_race_results_notification",
    "send_quali_results_notification",
    "send_new_season_reminder_notification",
    # Utils
    "format_weather_data",
    # Checker
    "check_notifications",
]

logger = logging.getLogger(__name__)

logger.debug("✅ notifications module loaded")
